"""
Strategy runner models for the execution engine.

Provides:
- OHLCVBar: Single candlestick data
- MarketSnapshot: Point-in-time market state for strategy evaluation
- EntryConfig, ExitConfig, RiskConfig: Nested configuration models
- ExecutionSpec: Runtime strategy instance definition
- StrategyEvaluation: Runner output with intents
"""

from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator

from app.schemas import TradeIntent


class OHLCVBar(BaseModel):
    """Single OHLCV candlestick."""

    ts: datetime = Field(..., description="Bar timestamp (UTC)")
    open: float = Field(..., description="Open price")
    high: float = Field(..., description="High price")
    low: float = Field(..., description="Low price")
    close: float = Field(..., description="Close price")
    volume: float = Field(..., description="Volume")


class MarketSnapshot(BaseModel):
    """
    Point-in-time market state for strategy evaluation.

    Contains OHLCV bars and derived convenience fields.
    Strategies use this to evaluate entry/exit conditions.
    """

    symbol: str = Field(..., description="Symbol this snapshot is for")
    ts: datetime = Field(..., description="Snapshot timestamp (UTC)")
    timeframe: str = Field(..., description="Timeframe: 'daily', '1h', etc.")

    # OHLCV window (most recent N bars)
    bars: list[OHLCVBar] = Field(
        ..., description="OHLCV bars, bars[-1] is current/latest"
    )

    # Derived convenience fields (OPTIONAL - strategy computes if missing)
    last_price: Optional[float] = Field(None, description="If None, use bars[-1].close")
    high_52w: Optional[float] = Field(
        None, description="52-week high. If None, compute from bars (excluding current)"
    )
    low_52w: Optional[float] = Field(
        None, description="52-week low. If None, compute from bars"
    )

    # Session flags
    is_eod: bool = Field(default=False, description="End-of-day flag for exit logic")

    @model_validator(mode="after")
    def validate_bars(self) -> "MarketSnapshot":
        """Validate bars constraints."""
        if len(self.bars) < 2:
            raise ValueError("MarketSnapshot requires at least 2 bars")
        if self.bars[-1].ts > self.ts:
            raise ValueError("Latest bar timestamp cannot exceed snapshot ts")
        return self


class EntryConfig(BaseModel):
    """Entry condition configuration."""

    type: str = Field(..., description="Entry type: 'breakout_52w_high', etc.")
    lookback_days: int = Field(
        default=252, description="Lookback period for 52-week high calculation"
    )


class ExitConfig(BaseModel):
    """Exit condition configuration."""

    type: str = Field(..., description="Exit type: 'eod' for end-of-day")


class RiskConfig(BaseModel):
    """Risk management configuration."""

    dollars_per_trade: float = Field(
        ..., gt=0, description="Position sizing in dollars"
    )
    max_positions: int = Field(
        default=5, ge=1, description="Maximum concurrent positions"
    )


class ExecutionSpec(BaseModel):
    """
    Runtime configuration for a strategy instance.

    This is what defines a running strategy: which symbols to trade,
    entry/exit conditions, and risk parameters.
    """

    # Identity
    strategy_id: str = Field(
        ..., description="Strategy TYPE key (e.g., 'breakout_52w_high')"
    )
    instance_id: UUID = Field(
        default_factory=uuid4,
        description="Runtime instance ID (auto-generated, used in intents)",
    )
    name: str = Field(..., description="Human-readable instance name")
    workspace_id: UUID = Field(..., description="Multi-tenant isolation")

    # Universe
    symbols: list[str] = Field(..., min_length=1, description="Explicit symbol list")
    timeframe: str = Field(..., description="Timeframe: 'daily', '1h', etc.")

    # Strategy configuration
    entry: EntryConfig = Field(..., description="Entry conditions")
    exit: ExitConfig = Field(..., description="Exit conditions")
    risk: RiskConfig = Field(..., description="Risk management")

    # Metadata
    enabled: bool = Field(default=True, description="Whether this instance is active")
    created_at: datetime = Field(
        default_factory=datetime.utcnow, description="Creation timestamp"
    )


class StrategyEvaluation(BaseModel):
    """
    Result of strategy evaluation.

    Contains the intents generated by the strategy runner
    for a specific symbol at a specific time.
    """

    spec_id: str = Field(..., description="ExecutionSpec.instance_id as string")
    symbol: str = Field(..., description="Symbol evaluated")
    ts: datetime = Field(..., description="Evaluation timestamp")
    evaluation_id: UUID = Field(
        default_factory=uuid4,
        description="Shared correlation_id for all intents in this evaluation",
    )
    intents: list[TradeIntent] = Field(
        default_factory=list, description="0, 1, or more intents"
    )
    signals: list[str] = Field(
        default_factory=list, description="Human-readable signal explanations"
    )
    metadata: dict = Field(
        default_factory=dict, description="Debug info (52w_high, price, etc.)"
    )
